### ISSUE TITLE
Intégration du menu des couches dans l'explorateur de QGIS ?

### ISSUE THREAD

**Issue by Doctor-Who** [geo2france/idg-qgis-plugin#11]
Pour ne pas multiplier les interfaces et panneaux, ne serait il pas pertinent de basculer l'arborescence des couches de l'IDG dans l’explorateur de QGIS ? A débattre sur l'intérêt / pertinence

![image](https://user-images.githubusercontent.com/5890416/150298130-d0f94752-31fb-40a7-b2cc-3b137680ac45.png)

NB : je viens de remarquer qu'il y a une fonction filtrage qui éviterait de réimplémenter une recherche ?

**Comment by vfabry** [comment]
Pas fan de cette proposition. J'aime bien l'idée que les couches servies par la plateforme ne soient pas noyées dans toutes les autres sources de données.

**Comment by jbdesbas** [comment]
![image](https://user-images.githubusercontent.com/6163107/194018469-35bdbb1a-30ac-458f-9b83-8add41d00e1e.png)

Avantage non négligeable : en plus d'une meilleure intégration dans QGIS, passer par l'explorateur permet de profiter des fonctionnalités actuelles et futures de celui-ci : 
- Filtrage simultané sur les couches du plugin et les autres couches de l'utilisateur
- Bookmarks
- Outils de propriétés (affichage des métadonnées, attributs et aperçu d'une couche sans l'ajouter au projet)

A vérifier, mais il me semble que l'explorateur est affiché par défaut dans les versions actuelles de QGIS.

Techniquement, cela consiste en l'ajout d'un _DataItemProvider_ au niveau de l'application.

**Comment by juliepierson** [comment]
Je trouve ça une bonne idée de tout regrouper dans l'explorateur, ça semble logique. Et ça résoudrait le fait que le panneau du plugin s'ouvre systématiquement à l'ouverture de QGIS, même si on l'a fermé la dernière fois (en fait ça ne gêne peut-être que moi, mais j'aime bien retrouver mon QGIS dans l'état où je l'ai laissé ;-) )

**Comment by Doctor-Who** [comment]
Un petit sondage auprès de la communauté pour recueillir vos avis : 
:question:  https://github.com/geo2france/idg-qgis-plugin/discussions/20

**Comment by bchartier** [comment]
> en fait ça ne gêne peut-être que moi, mais j'aime bien retrouver mon QGIS dans l'état où je l'ai laissé ;-) )

@juliepierson : je suis d'accord. Pareil pour moi, c'est gênant que ça revienne sans cesse. J'ai créé un ticket : #21

**Comment by bchartier** [comment]
> Pas fan de cette proposition. J'aime bien l'idée que les couches servies par la plateforme ne soient pas noyées dans toutes les autres sources de données.

On pourrait envisager les deux : garder la possibilité du panneau tout en intégrant les couches dans l'explorateur. Chacun utiliserait ce qui lui convient le mieux. Du coup, pour le sondage de @Doctor-Who : je ne sais pas quoi répondre.

**Comment by Doctor-Who** [comment]
J'ai remis à jour le sondage (désolé il faut revoter) et ajouter une option oui / non / les deux :)

**Comment by juliepierson** [comment]
Vous le savez peut-être déjà, mais je viens de voir dans la doc du panneau explorateur qu'on pouvait filtrer par type d'objet (WMS, WFS, WCS, script Python...) à partir du menu Préférences > Personnalisation de l'interface.
![image](https://user-images.githubusercontent.com/6247389/202508272-7c4d3849-3881-474c-8761-eb93e44148b7.png)
Un bon point pour l'explorateur donc !
