### ISSUE TITLE
Gérer les améliorations de l'outil par les releases et versions

### ISSUE THREAD

**Issue by Doctor-Who** [geo2france/idg-qgis-plugin#12]
Il est indispensable de versionner le plugin pour suivre la version dispo sur Github et la version publiée sur le dépôt officiel.
@bchartier on part sur une 1.0 ou tu considères qu'on est plutôt sur une 0.x ?

**Comment by Doctor-Who** [comment]
Tout à fait

**Comment by lecault** [comment]
Releases mises en place. A fermer ?

**Comment by Doctor-Who** [comment]
Effectivement, on ferme :)
