### ISSUE TITLE
Utiliser un fichier projet pour définir les couches

### ISSUE THREAD

**Issue by jbdesbas** [geo2france/idg-qgis-plugin#16]
A la place du fichier de configuration Json, permettre aux administrateurs de plateformes d'utiliser un fichier projet (.qgs ou .qgz, voir  .qlr ?) pour définir les couches (url, style, crs, métadonnées) et les groupes de couches.

**Comment by bchartier** [comment]
Ce ticket fait suite à la discussion #4 (discussion assez ancienne).

**Comment by jbdesbas** [comment]
L'utilisation d'un fichier projet devrait permettre de définir des styles #8 et de supporter davantage de formats (notamment les URL de fichiers distants geojson, COG...).
Penser à ajouter un check au niveau du plugin pour ignorer les couches locales qui aurait été ajoutées par erreur.
