### ISSUE TITLE
Rendre générique le plugin

### ISSUE THREAD

**Issue by jbdesbas** [geo2france/idg-qgis-plugin#17]
Rendre le plugin utilisable par plusieurs plateformes régionales ou locales.

Le plugin propose une liste par défaut de plateformes, l'utilisateur sélectionne la ou les plateformes dont il souhaite ajouter le contenu.

Laisser à l'utilisateur la possibilité d'ajouter d'autres plateformes (nom + url du fichier de configuration)

**Comment by gryckelynck** [comment]
Faut-il intégrer un peu de personnalisation aussi ?
Ex.: si je sélectionne DataGrandEst comme plateforme le titre du plugin s'adapte.
Peut-être dans une phase 2 de cette évolution...

**Comment by jbdesbas** [comment]
Dans une certaine limite oui, car un des intérêt de la généricité est de pouvoir ajouter plusieurs plateformes sur le plugin (par exemple une régionale et une plus locale).
On devrait pouvoir prévoir, si une seule plateforme est sélectionnée, de mettre le nom et logo de la plateforme en racine de l'arbre (#11) et adapter les titres des menus.
A voir par contre si ca ne crée pas trop de confusion pour l'utilisateur d'avoir un titre qui change ?

**Comment by bchartier** [comment]
> > A voir par contre si ca ne crée pas trop de confusion pour l'utilisateur d'avoir un titre qui change ?
> 
> C'est uniquement le nom de la connexion ou est-ce que ça peut perturber les chemins d'accès aux couches de l'IDG ?

Quand @gryckelynck parlait de changer le titre du plugin, c'était probablement dans le but d'afficher "Géo2France", "DataGrandEst", "Indigéo", "GéoBretagne" dans le menu des extensions et dans le titre du panneau. Je rejoins la remarque de @jbdesbas : voir le titre du menu ou du panneau changer risque d'être perturbant.

En plus, je me mets à la place d'un acteur qui avec le même plugin souhaite bénéficier des couches des deux plateformes car il intervient sur un territoire qui est en limite de deux régions. Dès qu'il ferait une manip, le truc changerait de nom. Hum, bof. Je sais bien que ce n'est pas top de dire cela alors que le plugin vise à rendre service aux plateformes de données et que celles-ci cherchent à se valoriser en s'affichant un peu via le nom du plugin. Ne pas mettre à jour le titre du plugin me paraît plus pertinent d'un point de vue de l'ergonomie (et on sait que des utilisateurs du plugin peuvent être facilement perturber par ce genre de détail) mais cela réduira la publicité faite aux plateformes. Ça vaudrait sûrement la peine de faire une réunion sur ce sujet en exposant de manière graphique ce que cela pourrait donner afin que toutes les parties prenantes puissent se projeter.

**Comment by Doctor-Who** [comment]
Ok je me projetais plus dans la vue d'arborescence du #11 
Ton cas d'usages est intéressant, ça voudrait dire que sous le menu IDG il faudrait pouvoir charger une à plusieurs plateformes ? 
A débattre.

**Comment by jbdesbas** [comment]
Je m’interroge. On peut, par défaut, proposer à l'utilisateur d'avoir lccès au contenu de toutes les plateformes.
Ca simplifiera beaucoup le plugin pour l'utilisateur, le **panneau de configuration devient optionnel** et peut permettre de désactiver certaines plateformes ou activer des plateformes "métiers" pas activées par défaut (utile ?). Vu que la simplicité d'usage est visiblement l'objectif principal du plugin, ca me semble à considérer.

On arrive à un parcours utilisateur très simple : 
1 installation du plugin --> 2 choix de la plateforme dans l'explorateur (cf #11) --> 3 affichage des données

**Comment by lecault** [comment]
D'ailleurs il y a sans doute une partie des données communes à toutes les plates-formes type IGN ou autres données nationales ?

En gros, un utilisateur à accès aux données nationales + celles de sa PF. Et s'il le désire peut tout avoir.

**Comment by jbdesbas** [comment]
Cf #42 pour les données nationales
