### ISSUE TITLE
Intégrer le paramétrage du plugin dans le panneau Options de QGIS

### ISSUE THREAD

**Issue by jbdesbas** [geo2france/idg-qgis-plugin#19]
Paramétrer le plugin IDG depuis le menu option de QGIS pour une meilleure intégration.

Voir exemple sur : https://gitlab.com/Oslandia/qgis/french_locator_filter/

![image](https://user-images.githubusercontent.com/6163107/194058681-b40ca0fd-a9a6-4dbd-be87-2fc6c514feb2.png)

**Comment by bchartier** [comment]
Ce serait sans doute plus propre.
Ça éviterait de surcharger le menu des extensions.

**Comment by juliepierson** [comment]
Si j'ai bien vu, ça fait partie des trucs que le [QGIS Plugin templater](https://oslandia.gitlab.io/qgis/template-qgis-plugin/) d'Oslandia mentionné en #18 implémente directement.
