### ISSUE TITLE
Ne pas ouvrir le panneau du plugin systématiquement au démarrage de QGIS

### ISSUE THREAD

**Issue by bchartier** [geo2france/idg-qgis-plugin#21]
Aujourd'hui le plugin s'ouvre systématiquement au démarrage de QGIS même si on l'a fermé lors de la dernière session.
À corriger pour qu'on retrouve QGIS dans le même état où on l'a fermé.

**Comment by jbdesbas** [comment]
L'issue n'est plus pertinente car il n'y a plus de panneau (intégré dans l'explorateur)
