### ISSUE TITLE
Fichier de licence

### ISSUE THREAD

**Issue by bchartier** [geo2france/idg-qgis-plugin#25]
Curieusement un fichier de licence est mentionné dans le README.md du projet mais le fichier en question n'est pas présent. Il faudrait en ajouter un.

**Comment by jbdesbas** [comment]
La licence BSD-3 vous convient ?

**Comment by bchartier** [comment]
> La licence BSD-3 vous convient ?

Oui, mais on a peut-être besoin d'une licence compatible avec [ça](https://gitlab.com/Oslandia/qgis/template-qgis-plugin) si on l'utile. (ou peut-être pas)

**Comment by jbdesbas** [comment]
Licence GPL2 ajoutée
