### ISSUE TITLE
Ne pas bloquer le thread principal

### ISSUE THREAD

**Issue by jbdesbas** [geo2france/idg-qgis-plugin#30]
Lors du téléchargement et du chargement des fichiers projets de config, le thread principal risque de bloquer plusieurs secondes (_freeze_ de l'interface).
- Utiliser [`QgsTask`](https://qgis.org/pyqgis/master/core/QgsTask.html#module-QgsTask)
- A l’initialisation du plugin, afficher un spinner pour les IDG en cours de téléchargement

Exemple : 
https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/tasks.html#examples

**Comment by bchartier** [comment]
Super. Merci beaucoup pour ton aide sur ce sujet.

[Juste pour être sûr que tu regardes au bon endroit dans le code, le code actuel est en chantier en se rebasant sur ton template CookieCutter. C'est dans la branche `dev`.]

**Comment by Guts** [comment]
> [Juste pour être sûr que tu regardes au bon endroit dans le code, le code actuel est en chantier en se rebasant sur ton template CookieCutter. C'est dans la branche `dev`.]

Tu fais bien de me le dire !

Je passais juste faire coucou :)

**Comment by jbdesbas** [comment]
Réaliser le téléchargement des fichier distant après le chargement de l'interface QGIS devrait permettre de résoudre la lenteur (voir les crash) de QGIS au démarrage provoquée par le plugin

```2023-07-26T08:18:27     INFO    PyQGIS Resource Browser chargé (paquet pyqgis_resource_browser)
2023-07-26T08:18:27     INFO    First Aid chargé (paquet firstaid)
2023-07-26T08:18:27     INFO    QuickOSM chargé (paquet QuickOSM)
2023-07-26T08:18:34     INFO    IDG chargé (paquet idg)
2023-07-26T08:18:34     INFO    Copy_Coords chargé (paquet copy_coords)
2023-07-26T08:18:34     INFO    Get WKT chargé (paquet QGIS3-getWKT)```

**Comment by jbdesbas** [comment]
@Guts merci pour tes exemples sur _qtribu_, le plugin ne retarde plus le lancement de QGIS ou ne freeze plus l'interface. 😀️
 
Si les fichiers sont téléchargés avec `QgsThread` (non bloquant), y a t'il encore un intérêt à différer le chargement du plugin après le chargement de l'interface QGIS ?
Le souci c'est que la fonction connectée au signal `initializationCompleted` n'est pas exécutée si le plugin est activé **après** le lancement de l'interface QGIS (activation du plugin depuis le gestionnaire d'extension, rechargement du plugin via Plugin Reloader ou tout autre méthode).
Je n'observe pas de différence sur le temps de lancement en exécutant le téléchargement des fichiers au moment de l'initialisation du plugin ou après le chargement de l'interface QGIS.

**Comment by Guts** [comment]
> @Guts merci pour tes exemples sur qtribu, le plugin ne retarde plus le lancement de QGIS ou ne freeze plus l'interface. grinning

Va falloir le mettre dans les crédits de votre plugin :laughing: !

> Le souci c'est que la fonction connectée au signal initializationCompleted n'est pas exécutée si le plugin est activé après le lancement de l'interface QGIS (activation du plugin depuis le gestionnaire d'extension, rechargement du plugin via Plugin Reloader ou tout autre méthode).

En effet, il faut prévoir de connecter les fonctions d'initialisation du plugin (téléchargement, authentification, config...) sur le signal d'activation du plugin également et qu'elles soient idempotentes au max.

> Je n'observe pas de différence sur le temps de lancement en exécutant le téléchargement des fichiers au moment de l'initialisation du plugin ou après le chargement de l'interface QGIS.

Je pense que c'est normal vu que le téléchargement est justement délégué à un ou plusieurs threads indépendants du thread principal, sur lequel sont faites les mesures.
