### ISSUE TITLE
Problème comportement du menu explorateur

### ISSUE THREAD

**Issue by Doctor-Who** [geo2france/idg-qgis-plugin#38]
Version plugin IDG : 0.1.0
Version QGIS : LTR 3.28.5
IDG active : Geo2France 

---

Testé sur un projet vierge.
Le menu contextuel ne se comporte pas comme les autres menus (exemple : connexion PG, flux WMS ou WFS) : 
- le glisser déposer ne fonctionne pas
- le clic droit : Afficher la couche ne fonctionne pas
- le clic droit : Afficher les métadonnées fonctionne correctement

La seule solution est de double cliquer sur la couche pour l'avoir dans QGIS

**Comment by jbdesbas** [comment]
Merci pour le retour.
OK pour le clic droit. :heavy_check_mark: 

Pour le drag&drop c'est un peu plus complexe : je l'avais désactiver volontairement car celui-ci charge directement l'url du layer (et non l'**objet** Layer), sans passer par le fichier projets. Si une symbologie est définie au niveau du fichier projet (pour un WFS par exemple), elle est donc perdu.
Il faudrait creuser plus pour voir si on peut agir plus finement sur le fonctionnement du drag&drop.

**Comment by Doctor-Who** [comment]
Si le clic droit passe ça sera déjà un beau fix.
Compris pour les aléas sur le WFS, effectivement potentiellement gênant
