### ISSUE TITLE
Gestion des projets

### ISSUE THREAD

**Issue by lecault** [geo2france/idg-qgis-plugin#40]
Version plugin IDG : 0.1.0
Version QGIS : 3.22

Dans les options du plugin, il serait bien pour un utilisateur de pouvoir supprimer des plates-formes (bouton -) ici : 
![image](https://user-images.githubusercontent.com/5269430/232812088-a1706f74-b836-432f-b640-16919de8caaf.png)

AUTRE POSSIBILITE : à la première ouverture du plugin, une fenêtre s'affiche permettant à l'utilisateur de sélectionner les plate-formes qu'il souhaite voir. Celles qu'il n'a pas sélectionnées sont désactivées pour son usage.
Dans le menu l'utilisateur voit la liste des plateformes avec une case à coché actif. Il garde la possibilité d'ajouter une nouvelle url.

**Comment by jbdesbas** [comment]
Plutôt la deuxième proposition pour moi : 
Différencier les plateformes "stock", c'est-à-dire celles déjà intégrées à l'installation du plugin et qu'il suffirait de cocher/décocher (ou masquer depuis l'explorateur); et les plateformes "custom" dont l'utilisateur du plugin doit indiquer l'URL.

**Comment by Doctor-Who** [comment]
> Plutôt la deuxième proposition pour moi : Différencier les plateformes "stock", c'est-à-dire celles déjà intégrées à l'installation du plugin et qu'il suffirait de cocher/décocher (ou masquer depuis l'explorateur); et les plateformes "custom" dont l'utilisateur du plugin doit indiquer l'URL.

QGIS mémorisera cela ? Au prochain lancement, comment faire pour réafficher une IDG qui aurait été masqué par erreur ?

**Comment by jbdesbas** [comment]
Oui, le plugin peut stocker de la config utilisateur. 

Tel que je l'imagine :
- on peut masquer une plateforme intuitivement depuis le panneau explorateur via un clique droit sur la plateforme
- Pour ré-afficher une plateforme masquée : 
  - Depuis le panneaux paramètres (1 checkbox par plateforme "stock")
  - Et pourquoi pas avec un clique droit sur l’icône IDG (root) du panneau explorateur

**Comment by lecault** [comment]
Pour moi on peut fermer cet issue ?
