### ISSUE TITLE
Créer un entrepôt IGN

### ISSUE THREAD

**Issue by Doctor-Who** [geo2france/idg-qgis-plugin#42]
Suite aux discussions du geoCom, il serait intéressant de mutualiser les flux ign nationaux au sein d'un groupe ign dédié au lieu de devoir parcourir chaque sous dossier idg.
Reste à voir le détail de cette co alimentation.
Proposer une première version (je peux me l'assigner si besoin d'aide)

**Comment by IGNF-Xavier** [comment]
Concernant les services W*S et TMS issus de la Géoplateforme, nous travaillons à proposer un projet qgz pour le plugin IDG qui est organisé dans sa première version en thématique puis service.
Les données concernent principalement celles proposées par l'infrastructure Géoportail puisque les premières à être dans l'infrastructure Géoplateforme.

Il reste à investiguer les suites données : 
- pour les nouvelles données qui seront diffusées par la Géoplateforme : conservation du thématique, mise en oeuvre d'un classement par producteur/territoire
- pour les services disponibles au travers de la Géoplateformes

**Comment by jbdesbas** [comment]
ok, cf #51
