### ISSUE TITLE
Problème SCR sur couche GeoBretagne

### ISSUE THREAD

**Issue by Doctor-Who** [geo2france/idg-qgis-plugin#47]
Version QGIS : 3.28.8 LTR
Version plugin : 0.2.1

A chaque lancement de QGIS  et se produit aussi quand je vais dans le menu Préférences, un message s'affiche :
![Capture d’écran du 2023-07-26 16-11-44](https://github.com/geo2france/idg-qgis-plugin/assets/5890416/e19e50c4-0303-4e8c-b8fd-8099bbd13de1)

Cela ne se produit que si l'utilisateur a paramétré QGIS pour demander le SCR en cas de SCR inconnu.
La couche en question est le raster situé dans Environnement > Espaces protégés > Réserve Nationale de Chasse et de la Faune Sauvage

Ping @smevel

**Comment by smevel** [comment]
merci @Doctor-Who couche supprimée et projet actualisé :)

**Comment by Doctor-Who** [comment]
Merci pour le fix rapide, ce matin au chargement de QGIS, j'ai toujours le message du SCR sur la couche.
Mais je pense que c'est lié à une seconde erreur : 

`Erreur: Le téléchargement du fichier projet GéoBretagne a échoué.`

**Comment by jbdesbas** [comment]
C'était visiblement causé par une indispo temporaire du serveur.
Merci pour le fix
