### ISSUE TITLE
default_idg.json avec Géoplateforme

### ISSUE THREAD

**Issue by IGNF-Xavier** [geo2france/idg-qgis-plugin#51]
Bonjour,
VOici le default_idg.json avec lien vers le projet qgz de la Géoplateforme.
Je n'arrive pas à effectuer de pull donc merci d'avance pour la mise-à-jour

[default_idg.json](https://github.com/geo2france/idg-qgis-plugin/files/13471195/default_idg.json)

**Comment by jbdesbas** [comment]
OK sur c78269be7415bb280f3a5f1ca3db851a5dc2261b
La nouvelle plateforme devrait apparaître pour les utilisateurs au prochain lancement de QGIS.
N'hésite pas à ré-ouvrir le ticket si il y a un souci.
