### ISSUE TITLE
Mise à jour des couches cadastre (PCI vecteur) sur les HdF

### ISSUE THREAD

**Issue by vfabry** [geo2france/idg-qgis-plugin#54]
Les 4 couches cadastre sur lesquelles il faut pointer sont :
* geo_batiment_2023
* geo_parcelle_2023
* geo_section_2023
* geo_commune_2023
Merci !
Vincent

**Comment by jbdesbas** [comment]
@vfabry Et concernant "Parcelles des personnes morales", il y a une couche de remplacement ?

**Comment by vfabry** [comment]
et pour personnes morales : parcellaire_majic_personnes_morales_2022_publi (https://www.geo2france.fr/geoserver/geo2france/ows )

**Comment by jbdesbas** [comment]
Fichier mis à jour ici : https://www.geo2france.fr/public/qgis3/plugins/geo2france/geo2france.qgz
