### ISSUE TITLE
Mise à jour d'un projet non répercuté dans le plugin

### ISSUE THREAD

**Issue by lecault** [geo2france/idg-qgis-plugin#62]
Suite à notre réunion j'ai mis à jour le projet GéoBretagne ici : https://geobretagne.fr/pub/plugin-qgis/config-idg-geobretagne.qgs

Or, dans le plugin, je vois toujours l'ancienne version : exemple dans le groupe Fonds raster, il n'y a plus de catégorie IGN.

**Comment by lecault** [comment]
Je viens d'essayer en transformation mon projet en qgz (branche dev) j'ai le même résultat...

**Comment by lecault** [comment]
Bon je viens de rouvrir le plugin et là les couches affichées sont bien à jour...

**Comment by Doctor-Who** [comment]
Si le problème ne s'est pas reproduit, je te propose de clôturer cette issue ?
