### ISSUE TITLE
Impossible de charger l'extension

### ISSUE THREAD

**Issue by Guts** [geo2france/idg-qgis-plugin#65]
Salut,

En vue de la conf QGIS FR qui se tient cette semaine, nous concoctons un profil QGIS avec tous les plugins évoqués pendant la conférence donc le vôtre.

Nous ne l'avons trouvé ni sur le dépôt officiel ni sur un dépôt personnalisé public. Nous essayons donc de l'installer à partir du zip des release Github, mais j'ai cette erreur : 

![image](https://github.com/geo2france/idg-qgis-plugin/assets/1596222/8fd63588-76ba-472e-9ef4-a3570d42e927)

cc @florentfgrs

**Comment by Guts** [comment]
Pardon, j'ai été trop vite, en fait le ZIP contient le code source ET le plugin... bon je refais la manip alors.

**Comment by landryb** [comment]
de ce que je vois la 0.2.4 est dispo dans les plugins officiels, il faut juste toggler le flag experimental pour l'avoir ?

https://plugins.qgis.org/plugins/idg/#plugin-versions

**Comment by Guts** [comment]
Merci, on n'a pas les yeux en face des trous. Histoire de ne pas perdre complètement la face 😁 , je suggère d'ajouter le lien sur le Readme ou dans les méta-données du projet Github !

**Comment by jbdesbas** [comment]
Par exemple [ici](https://github.com/geo2france/idg-qgis-plugin?tab=readme-ov-file#installation) @Guts 😉
Merci pour ton retour (et le profile QGIS), je vais regarder pour que ca soit un peu plus explicite sur le readme.

**Comment by Guts** [comment]
> Par exemple [ici](https://github.com/geo2france/idg-qgis-plugin?tab=readme-ov-file#installation) @Guts ? 😉
> Merci pour ton retour (et le profile QGIS), je vais regarder pour que ca soit un peu plus explicite sur le readme.

Plutôt ici

![Screenshot_20240325-154108.png](https://github.com/geo2france/idg-qgis-plugin/assets/1596222/f8e7e21f-bae6-45ca-a710-b7d997d5571f)

**Comment by florentfgrs** [comment]
Excusez-moi pour la fausse alerte, c'est moi qui ai indiqué à @Guts que je ne le trouvais pas sur le repo officiel QGIS, je n'avais juste pas activé les plugins expérimentaux.
