### ISSUE TITLE
Données IGN

### ISSUE THREAD

**Issue by vfabry** [geo2france/idg-qgis-plugin#7]
Je constate que chez certains partenaires de la plateforme, la mise en open data des données IGN n'est pas connue. Certains utilisent encore d'anciennes données, qui ont été mises à jour depuis.
Je me demande si on ne pourrait pas faire une section IGN dans le plugin, qui donnerait facilement accès aux données disponibles en open data. Je ne sais pas quelle serait la meilleure façon d'organiser cela, vu que le plugin est organisé par thème plutôt que par producteur.

Vincent

**Comment by jbdesbas** [comment]
Géoplateforme ajoutée c78269be7415bb280f3a5f1ca3db851a5dc2261b
