### ISSUE TITLE
Déplacer des fichiers Python hors de toolbelt

### ISSUE THREAD

**Issue by bchartier** [geo2france/idg-qgis-plugin#70]
Je me demande si le répertoire toolbelt a vocation à contenir certains de nos fichiers Python comme browser.py, tree_node.py, remote_platforms.py... J'ai l'impression qu'il a été fait pour contenir du code utilitaire qui n'est pas spécifique au plugin.
J'aurais tendance à mettre ces fichiers dans un autre répertoire pour que ce soit plus clair.

**Comment by jbdesbas** [comment]
Je link avec #66 (organisation du code)

**Comment by Guts** [comment]
Une des pratiques et de stocker ce qui est lié à la logique propre à un programme dans un dossier `core` ou `logic`. `toolbelt` étant un peu comme `utils` mais moins "conflictuel" (on trouve du `utils` partout) et contient plutôt du code réutilisable d'un projet similaire à l'autre (ici un plugin QGIS).

**Comment by bchartier** [comment]
> Une des pratiques et de stocker ce qui est lié à la logique propre à un programme dans un dossier `core` ou `logic`. `toolbelt` étant un peu comme `utils` mais moins "conflictuel" (on trouve du `utils` partout) et contient plutôt du code réutilisable d'un projet similaire à l'autre (ici un plugin QGIS).

Merci pour cet éclairage.
Ça m'arrange bien car c'est cohérent avec ma proposition de sortir ce qui est vraiment spécifique de ce projet du dossier toolbelt.
E n plus j'ai le sentiment que cela réduirait le risque d'imports cycliques.

**Comment by bchartier** [comment]
Discussion d'aujourd'hui avec @jbdesbas : déplacer les actions de `plugin_actions.py` vers le dossier `gui`.

**Comment by bchartier** [comment]
J'ai déplacé la dernière suggestion dans un autre ticket car ce n'est pas directement lié à toolbelt : #89
