### ISSUE TITLE
Paramètre config_files_download_at_startup inutilisé

### ISSUE THREAD

**Issue by bchartier** [geo2france/idg-qgis-plugin#71]
J'ai l'impression que le paramètre `config_files_download_at_startup  ` n'est plus utilisé par le plugin.
Le fichier JSON qui décrit l'ensemble des plateformes présentes par défaut est téléchargé systématiquement au démarrage du plugin.
La constante qui gère cela est `CONFIG_FILES_DOWNLOAD_AT_STARTUP` mais le test de cette valeur est réalisé par la fonction `need_download_tree_config_file` mais cette dernière n'est pas du tout utilisée.

**Est-ce que nous souhaitons que le plugin télécharge systématiquement ce fichier ou non ?**
Si oui, alors il faudrait supprimer ce paramètre.
Si non, je peux ajouter le test au bon endroit.
Perso je préfèrerais qu'on puisse déactiver le téléchargement ne serait-ce que pour des besoins de debug.

**Comment by jbdesbas** [comment]
Par cohérence, il faudrait pouvoir activer/désactiver : 
- Le téléchargement de la liste des projets (defaults_idg.json depuis le github du plugin)
- Le téléchargement des fichiers qgs/qgz

Pour simplifier, je pense que les 2 devraient être contrôlé par le même paramètre (ca n'a pas tellement de sens de MAJ la liste des projets sans MAJ les fichiers projets, et vice-versa )

**Comment by bchartier** [comment]
> Pour simplifier, je pense que les 2 devraient être contrôlés par le même paramètre (ca n'a pas tellement de sens de MAJ la liste des projets sans MAJ les fichiers projets, et vice-versa ). En gardant à chaque fois le même principe : si le fichier n'existe pas, il faut dans tous les cas le télécharger.

Oui, d'accord avec ça.

> En lien, il faudrait proposer un bouton pour forcer le téléchargements des fichiers (surtout si on l'a désactiver au démarrage)

Dans la fenêtre de paramétrage ?

**Comment by bchartier** [comment]
Menu contextuel ajouté dans c1e50cf3bb805cf0e2fa668c746506a0bc374303
C'est mis aussi dans le menu principal du plugin.
Est-ce qu'on a besoin de rendre accessible cette fonction dans la fenêtre dlg_settings ? Pas sûr.
