### ISSUE TITLE
IDG non chargées dans l'explorateur

### ISSUE THREAD

**Issue by bchartier** [geo2france/idg-qgis-plugin#75]
Le code actuel dans la branche dev ne crée pas systématiquement la partie IDG :
https://github.com/geo2france/idg-qgis-plugin/blob/d4252ee377054c69f5d19053988ff9b2ab14651d/plugin/idg/plugin_main.py#L79-L82

Ce n'est fait que si les fichiers de config doivent être téléchargés.
Si les settings indiquent que les fichiers de configuration ne doivent pas être téléchargés, le provider à intégrer à l'explorateur est créé mais n'est pas inscrit dans le registre. Cela pose ensuite des problèmes dans la partie dlg_settings.py :
https://github.com/geo2france/idg-qgis-plugin/blob/d4252ee377054c69f5d19053988ff9b2ab14651d/plugin/idg/gui/dlg_settings.py#L158

Le registre n'est pas capable de fournir le provider ce qui entraine la levée d'une exception dans la suite du code.

Actions à réaliser :
- faire en sorte que le provider soit inscrit systématiquement dans le registre de l'explorateur

**Comment by jbdesbas** [comment]
Ok. On est censé n'avoir que 2 cas de figures (https://github.com/geo2france/idg-qgis-plugin/issues/71#issuecomment-2242441194)

- On télécharger _default_idg.json_ + les QGZ : `registry.addProvider ` doit être exécuté APRÈS la fin de tous les téléchargements
- On ne télécharge rien : `registry.addProvider `  peut être exécuté immédiatement
