### ISSUE TITLE
Arborescence des fichiers téléchargés

### ISSUE THREAD

**Issue by jbdesbas** [geo2france/idg-qgis-plugin#79]
Les fichiers téléchargés (_default_idgs.json_ + QGZ + PNG) sont "en vrac" dans un fichier `config` à la racine du plugin.

Rendre plus lisible avec : 
- un dossier par IDG (QGS/QGZ + image png)
- le fichiers _default_idgs.json` à la racine
- renommer `config` en `remote`

Exemple : 
```
remote
  - default_idgs.json
  - idgX
    - idgX.qgs
    - idgX.png
  - idgN
   - idgN.qgz
   - idgN.png
  - ...  
```

**Comment by bchartier** [comment]
Quand tu mets `idgX`, ça correspond à `idg_id` de la classe `Plateform` j'imagine.

**Comment by jbdesbas** [comment]
Démarche : 
On garde le fichier `config` pour le `default_idg.json` d'origine (inclus dans le paquet du plugin).
Le fichier `default_idg.json` le plus à jours (télécharger par le plugin) est dans `remote`.

Le dossier remote peut-être supprimé, les fichiers (ficher projets + logo + json) seront retéléchargés.

**Comment by jbdesbas** [comment]
Dossier `remote`
![image](https://github.com/user-attachments/assets/4a3e09cd-d1e6-44f7-b7a5-117abd24ad36)
