### ISSUE TITLE
couches WFS : associer un style

### ISSUE THREAD

**Issue by vfabry** [geo2france/idg-qgis-plugin#8]
Est-ce qu'on peut déclarer une couche WFS et l'associer avec un style stocké quelque part ?
Vincent

**Comment by bchartier** [comment]
Non, dans la version actuelle du plugin ce n'est pas possible.
Mais ce serait possible si on envisage la convergence discutée là : https://github.com/geo2france/idg-qgis3-plugin/discussions/4

**Comment by vfabry** [comment]
OK, merci
