### ISSUE TITLE
Intégrer une fonction recherche similaire à la version GeoBretagne

### ISSUE THREAD

**Issue by Doctor-Who** [geo2france/idg-qgis-plugin#9]

**Comment by bchartier** [comment]
Le commit lié à la recherche chez GéoBretagne :
https://github.com/geobretagne/qgis-plugin/commit/f5fb8dd93c5748391a150f64b7d6ab38e43caa02

Sinon, pour que ce soit plus simple il faudrait qu'on ait un seul repo Github pour toutes les plateformes et qu'on rende la chose  générique sans référence à telle ou telle plateforme.

**Comment by Doctor-Who** [comment]
Excellente idée, sinon nous allons nous épuiser à backporter ces nouvelles fonctionnalités dans les plugins respectifs ...
@vfabry est-ce qu'on pourrait organiser une réunion à ce sujet avec les autres IDG ?

**Comment by vfabry** [comment]
ça voudrait dire un plugin unique, et après l'utilisateur indique dans quelle région il est ?
(OK pour organiser une réunion avec DataGrandEst et GéoBretagne)

**Comment by Doctor-Who** [comment]
Ou un plugin unique qui, via un fichier de conf spécifique ensuite implémenté, permet la génération des plugins IDG.
Je sais que coté packaging ça se fait mais est-ce jouable d'après ton expérience ( @bchartier ) sur un plugin QGIS ?

**Comment by jbdesbas** [comment]
Les couches sont maintenant dans le panneau "Navigateur" de QGIS et le filtrage texte y est supporté nativement (avec possibilité d'expression régulière, joker, sensibilité ou non à la casse)
